### ISSUE TITLE
blob.h: no such file or directory

### ISSUE THREAD

**Issue by atomsymbol** [tarceri/Mesa#3]
From build log:

/var/tmp/portage/media-libs/mesa-9999/work/mesa-9999/src/mesa/state_tracker/st_glsl_to_tgsi.cpp:33:18: fatal error: blob.h: No such file or directory
 #include "blob.h

**Comment by atomsymbol** [comment]
[build.log](http://atom-symbol.net/f/2017-02-04/media-libs:mesa-9999:20170204-121255.log)

**Comment by tarceri** [comment]
I've force pushed a fix. Thanks.

**Comment by atomsymbol** [comment]
Thanks. Tested it on Shadow of Mordor. The cache works OK for this game.
