### ISSUE TITLE
Google Chrome rendering issues with GLSL cache

### ISSUE THREAD

**Issue by atomsymbol** [tarceri/Mesa#4]
Hello

Steps to reproduce the issue:

    export MESA_GLSL_CACHE_ENABLE=1
    export MESA_GLSL_CACHE_DIR="$HOME/.cache/mesa"
    rm -rf "$HOME/.cache/mesa"
    google-chrome     # some minor rendering issues
    <exit Google Chrome>
    google-chrome     # serious rendering issues

**Comment by tarceri** [comment]
Yep. That's pretty bad, thanks for reporting.

**Comment by tarceri** [comment]
Fixed in shader-cache-radeonsi4
