### ISSUE TITLE
Afraid we'll never see shader cache for i965 if effort to push upstream dropped

### ISSUE THREAD

**Issue by sheepdestroyer** [tarceri/Mesa#7]
I know you have other priorities but, seeing how your proposal on ML to take upstreaming effort responsibility from you wasn't replied to, I fear that this feature may be dropped.

Will there be a mean to get it anyway, through valve's mesa fork or something?

**Comment by tarceri** [comment]
No need to worry. Someone from Intel has picked up the work :)
